"""Source-owned inventory of WS03-03A recent-auth protected actions."""

from __future__ import annotations

from dataclasses import dataclass

from backend.services.auth_service import RECENT_AUTH_REQUIRED_CODE


@dataclass(frozen=True)
class RecentAuthProtectedAction:
    action_id: str
    actor: str
    method: str
    route_template: str
    enforcement_dependency: str
    frontend_caller: str
    protections: tuple[str, ...]
    provider_mfa_dependency: str
    recent_auth_required: bool = True


RECENT_AUTH_PROTECTED_ACTIONS: tuple[RecentAuthProtectedAction, ...] = (
    RecentAuthProtectedAction(
        action_id="self_account_delete",
        actor="current_user",
        method="DELETE",
        route_template="/auth/account",
        enforcement_dependency="require_recent_app_user",
        frontend_caller="useDeleteAccountSettings",
        protections=(
            "typed confirmation",
            "existing account deletion workflow guards",
            "Firebase provider remains account authority",
        ),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="admin_user_role_change",
        actor="admin",
        method="PATCH",
        route_template="/admin/users/{user_id}/role",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="AdminUserDetailPage role action",
        protections=("active admin", "final-admin guard", "idempotency key", "audit action"),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="admin_user_delete",
        actor="admin",
        method="POST",
        route_template="/admin/users/{user_id}/delete",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="AdminUserDeletePreviewModal",
        protections=("active admin", "current-state token", "idempotency key", "audit action"),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="admin_user_restrict_hosting",
        actor="admin",
        method="POST",
        route_template="/admin/users/{user_id}/restrict-hosting",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="AdminUserHostingRestrictionModal",
        protections=(
            "active admin",
            "preview token",
            "idempotency key",
            "hosting capability state",
            "audit action",
            "account-security notification",
        ),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="admin_user_restore_hosting",
        actor="admin",
        method="POST",
        route_template="/admin/users/{user_id}/restore-hosting",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="AdminUserHostingRestorationModal",
        protections=(
            "active admin",
            "idempotency key",
            "hosting capability state",
            "audit action",
            "account-security notification",
        ),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="admin_user_suspend",
        actor="admin",
        method="POST",
        route_template="/admin/users/{user_id}/suspend",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="AdminUserSuspensionModal",
        protections=("active admin", "current-state token", "idempotency key", "audit action"),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="admin_user_unsuspend",
        actor="admin",
        method="POST",
        route_template="/admin/users/{user_id}/unsuspend",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="AdminUserUnsuspensionModal",
        protections=("active admin", "idempotency key", "audit action"),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="admin_financial_outcome_create",
        actor="admin",
        method="POST",
        route_template="/admin/money/financial-outcomes",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="adminFinancialOutcomeApi",
        protections=("active admin", "idempotency key", "money issue linkage"),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="admin_money_issue_resolve",
        actor="admin",
        method="POST",
        route_template="/admin/money/issues/{money_issue_id}/resolve",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="AdminMoneyIssuePage",
        protections=("active admin", "current issue state", "idempotency key"),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="admin_money_issue_retry_credit",
        actor="admin",
        method="POST",
        route_template="/admin/money/issues/{money_issue_id}/retry-credit",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="AdminMoneyIssuePage",
        protections=("active admin", "current issue state", "idempotency key"),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="admin_refund_retry",
        actor="admin",
        method="POST",
        route_template="/admin/money/refunds/{refund_id}/retry",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="AdminMoneyIssuePage/AdminMoneyRefundPage",
        protections=("active admin", "provider reconciliation", "idempotency key"),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="admin_refund_reconcile",
        actor="admin",
        method="POST",
        route_template="/admin/money/refunds/{refund_id}/reconcile",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="AdminMoneyRefundPage",
        protections=("active admin", "provider reconciliation", "idempotency key"),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="admin_payment_event_repair",
        actor="admin",
        method="PATCH",
        route_template="/payment-events/{payment_event_id}",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="no-current-frontend-caller",
        protections=(
            "active admin",
            "provider event identity immutability",
            "payment linkage validation",
            "processing result repair bounds",
        ),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="admin_game_credit_issue",
        actor="admin",
        method="POST",
        route_template="/admin/game-credits/issue",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="admin money credit workflows",
        protections=("active admin", "source validation", "idempotency key", "ledger row"),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="admin_game_credit_reverse",
        actor="admin",
        method="POST",
        route_template="/admin/game-credits/{game_credit_id}/reverse",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="admin money credit workflows",
        protections=("active admin", "usage guard", "idempotency key", "ledger row"),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="official_game_cancel_execute",
        actor="admin",
        method="POST",
        route_template="/admin/official-games/{game_id}/cancel",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="AdminOfficialGamePage",
        protections=("active admin", "preview token", "provider refunds", "audit action"),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="official_game_player_removal_execute",
        actor="admin",
        method="POST",
        route_template="/admin/official-games/{game_id}/participants/{participant_id}/remove",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="AdminOfficialGamePage",
        protections=(
            "active admin",
            "preview token",
            "paid booking/payment state checks",
            "credit/refund handling",
            "waitlist advancement",
            "audit action",
        ),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="admin_community_game_cancellation",
        actor="admin",
        method="POST",
        route_template="/admin/community-games/{game_id}/cancel",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="AdminCommunityGameActionModal",
        protections=(
            "active admin",
            "idempotency key",
            "current game state",
            "row locking",
            "cancellation workflow rules",
            "audit action",
            "host/user notices",
            "shared cancellation payment/credit handling where applicable",
        ),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="admin_need_a_sub_post_removal",
        actor="admin",
        method="POST",
        route_template="/admin/need-a-sub/{post_id}/remove",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="AdminNeedASubRemovalModal",
        protections=(
            "active admin",
            "idempotency key",
            "current post state",
            "row locking",
            "terminal removal workflow",
            "audit action",
            "owner/requester notices",
            "request and chat closure",
        ),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="admin_game_soft_delete",
        actor="admin",
        method="DELETE",
        route_template="/games/{game_id}",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="no-current-frontend-caller",
        protections=(
            "active admin",
            "official-game rejection",
            "soft-delete lifecycle state",
            "review-case closure where applicable",
        ),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="admin_venue_soft_delete",
        actor="admin",
        method="DELETE",
        route_template="/venues/{venue_id}",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="no-current-frontend-caller",
        protections=(
            "active admin",
            "venue active-state guard",
            "soft-delete lifecycle fields",
        ),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="platform_notice_create",
        actor="admin",
        method="POST",
        route_template="/admin/platform-notices",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="AdminPlatformNoticesPage",
        protections=("active admin", "idempotency key", "recipient selection audit"),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="platform_notice_cancel",
        actor="admin",
        method="POST",
        route_template="/admin/platform-notices/{notice_id}/cancel",
        enforcement_dependency="require_recent_active_admin",
        frontend_caller="AdminPlatformNoticesPage",
        protections=("active admin", "current notice state", "audit action"),
        provider_mfa_dependency="deferred_to_ws03_03b",
    ),
    RecentAuthProtectedAction(
        action_id="saved_payment_method_default_change",
        actor="current_user",
        method="PATCH",
        route_template="/user-payment-methods/{payment_method_id}/default",
        enforcement_dependency="require_recent_active_user",
        frontend_caller="PaymentMethodsPage",
        protections=("active user", "owned saved-card check", "persistent account-state change"),
        provider_mfa_dependency="not_required_for_current_user_saved_card_management",
    ),
    RecentAuthProtectedAction(
        action_id="saved_payment_method_detach",
        actor="current_user",
        method="DELETE",
        route_template="/user-payment-methods/{payment_method_id}",
        enforcement_dependency="require_recent_active_user",
        frontend_caller="PaymentMethodsPage",
        protections=("active user", "owned saved-card check", "persistent account-state change"),
        provider_mfa_dependency="not_required_for_current_user_saved_card_management",
    ),
)

RECENT_AUTH_PROTECTED_ROUTE_KEYS = frozenset(
    (action.method, action.route_template) for action in RECENT_AUTH_PROTECTED_ACTIONS
)

RECENT_AUTH_PUBLIC_ERROR_CODE = RECENT_AUTH_REQUIRED_CODE
