from __future__ import annotations

from sqlalchemy.orm import Session

from backend.models import Game, User, Venue
from backend.scripts.demo_data.helpers import demo_uuid, ends_at, now_utc, starts_at, upsert_by_id
from backend.scripts.demo_data.users import ADMIN_KEY

DEMO_GAMES = [
    {
        "key": "intentional-7pm",
        "venue_key": "intentional-sports",
        "title": "Saturday Night 7v7",
        "game_type": "official",
        "day_offset": 0,
        "hour": 19,
        "minute": 0,
        "format_label": "7v7",
        "environment_type": "indoor",
        "total_spots": 16,
        "price_per_player_cents": 1200,
        "target_participants": 14,
    },
    {
        "key": "rauner-indoor-730pm",
        "venue_key": "rauner-ymca-indoor",
        "title": "Fast Indoor 5v5",
        "game_type": "official",
        "day_offset": 0,
        "hour": 19,
        "minute": 30,
        "format_label": "5v5",
        "environment_type": "indoor",
        "total_spots": 12,
        "price_per_player_cents": 1100,
        "target_participants": 4,
    },
    {
        "key": "skinner-745pm",
        "venue_key": "skinner-park",
        "title": "West Loop Pickup",
        "game_type": "official",
        "day_offset": 0,
        "hour": 19,
        "minute": 45,
        "format_label": "7v7",
        "environment_type": "outdoor",
        "total_spots": 14,
        "price_per_player_cents": 1200,
        "target_participants": 6,
    },
    {
        "key": "skyline-755pm",
        "venue_key": "skyline-pitch",
        "title": "Skyline Lights",
        "game_type": "official",
        "day_offset": 0,
        "hour": 19,
        "minute": 55,
        "format_label": "5v5",
        "environment_type": "outdoor",
        "total_spots": 10,
        "price_per_player_cents": 1000,
        "target_participants": 3,
    },
    {
        "key": "harrison-8pm",
        "venue_key": "harrison-park",
        "title": "Pilsen 7v7",
        "game_type": "official",
        "day_offset": 0,
        "hour": 20,
        "minute": 0,
        "format_label": "7v7",
        "environment_type": "outdoor",
        "total_spots": 12,
        "price_per_player_cents": 900,
        "target_participants": 5,
    },
    {
        "key": "livingston-830pm",
        "venue_key": "livingston-park",
        "title": "Uptown Under Lights",
        "game_type": "official",
        "day_offset": 0,
        "hour": 20,
        "minute": 30,
        "format_label": "7v7",
        "environment_type": "outdoor",
        "total_spots": 16,
        "price_per_player_cents": 1200,
        "target_participants": 8,
    },
    {
        "key": "british-school-845pm",
        "venue_key": "british-international-school-of-chicago-south-loop",
        "title": "South Loop Indoor",
        "game_type": "official",
        "day_offset": 0,
        "hour": 20,
        "minute": 45,
        "format_label": "5v5",
        "environment_type": "indoor",
        "total_spots": 10,
        "price_per_player_cents": 1000,
        "target_participants": 2,
    },
    {
        "key": "rauner-outdoor-915pm",
        "venue_key": "rauner-ymca-outdoor",
        "title": "Community Run 7v7",
        "game_type": "community",
        "host_key": "host-marcus",
        "day_offset": 0,
        "hour": 21,
        "minute": 15,
        "format_label": "7v7",
        "environment_type": "outdoor",
        "total_spots": 12,
        "price_per_player_cents": 1100,
        "target_participants": 6,
    },
    {
        "key": "skyline-community-945pm",
        "venue_key": "skyline-pitch",
        "title": "Late Night Community 5s",
        "game_type": "community",
        "host_key": "host-sofia",
        "day_offset": 0,
        "hour": 21,
        "minute": 45,
        "format_label": "5v5",
        "environment_type": "outdoor",
        "total_spots": 10,
        "price_per_player_cents": 1000,
        "target_participants": 3,
    },
    {
        "key": "intentional-sunday-6pm",
        "venue_key": "intentional-sports",
        "title": "Sunday Indoor 5v5",
        "game_type": "official",
        "day_offset": 1,
        "hour": 18,
        "minute": 0,
        "format_label": "5v5",
        "environment_type": "indoor",
        "total_spots": 12,
        "price_per_player_cents": 1200,
        "target_participants": 7,
    },
    {
        "key": "skinner-sunday-7pm",
        "venue_key": "skinner-park",
        "title": "Sunday West Loop 7s",
        "game_type": "official",
        "day_offset": 1,
        "hour": 19,
        "minute": 0,
        "format_label": "7v7",
        "environment_type": "outdoor",
        "total_spots": 14,
        "price_per_player_cents": 1100,
        "target_participants": 9,
    },
]


def seed_games(db: Session, users: dict[str, User], venues: dict[str, Venue]) -> dict[str, Game]:
    seeded_games: dict[str, Game] = {}
    timestamp = now_utc()
    admin = users[ADMIN_KEY]

    for game_data in DEMO_GAMES:
        venue = venues[game_data["venue_key"]]
        game_start = starts_at(game_data["day_offset"], game_data["hour"], game_data["minute"])
        game_id = demo_uuid(f"game:{game_data['key']}")
        is_community = game_data["game_type"] == "community"
        host = users[game_data["host_key"]] if is_community else None

        seeded_games[game_data["key"]] = upsert_by_id(
            db,
            Game,
            game_id,
            {
                "game_type": game_data["game_type"],
                "publish_status": "published",
                "game_status": "scheduled",
                "title": game_data["title"],
                "description": None,
                "venue_id": venue.id,
                "venue_name_snapshot": venue.name,
                "address_snapshot": venue.address_line_1,
                "city_snapshot": venue.city,
                "state_snapshot": venue.state,
                "neighborhood_snapshot": venue.neighborhood,
                "host_user_id": host.id if host is not None else None,
                "created_by_user_id": host.id if host is not None else admin.id,
                "starts_at": game_start,
                "ends_at": ends_at(game_start),
                "timezone": "America/Chicago",
                "sport_type": "soccer",
                "format_label": game_data["format_label"],
                "environment_type": game_data["environment_type"],
                "total_spots": game_data["total_spots"],
                "price_per_player_cents": game_data["price_per_player_cents"],
                "currency": "USD",
                "minimum_age": None,
                "allow_guests": True,
                "max_guests_per_booking": 2,
                "waitlist_enabled": True,
                "is_chat_enabled": True,
                "policy_mode": "custom_hosted" if is_community else "official_standard",
                "custom_rules_text": (
                    "Bring a light and dark shirt. Host will confirm final teams."
                    if is_community
                    else None
                ),
                "custom_cancellation_text": None,
                "game_notes": None,
                "arrival_notes": None,
                "parking_notes": None,
                "published_at": timestamp,
                "cancelled_at": None,
                "cancelled_by_user_id": None,
                "cancel_reason": None,
                "completed_at": None,
                "completed_by_user_id": None,
                "deleted_at": None,
                "updated_at": timestamp,
            },
        )

    return seeded_games
