from fastapi.testclient import TestClient


def test_core_routes_are_registered(client: TestClient):
    registered_routes = {
        (method, route.path)
        for route in client.app.routes
        for method in route.methods
        if method not in {"HEAD", "OPTIONS"}
    }
    expected_routes = {
        ("GET", "/"),
        ("GET", "/db-health"),
        ("POST", "/users"),
        ("GET", "/users"),
        ("GET", "/users/{user_id}"),
        ("PATCH", "/users/{user_id}"),
        ("DELETE", "/users/{user_id}"),
        ("POST", "/user-settings"),
        ("GET", "/user-settings/{user_id}"),
        ("PATCH", "/user-settings/{user_id}"),
        ("POST", "/user-stats"),
        ("GET", "/user-stats"),
        ("GET", "/user-stats/{user_id}"),
        ("PATCH", "/user-stats/{user_id}"),
        ("POST", "/user-payment-methods"),
        ("GET", "/user-payment-methods"),
        ("GET", "/user-payment-methods/{payment_method_id}"),
        ("PATCH", "/user-payment-methods/{payment_method_id}"),
        ("POST", "/venues"),
        ("GET", "/venues"),
        ("GET", "/venues/{venue_id}"),
        ("PATCH", "/venues/{venue_id}"),
        ("DELETE", "/venues/{venue_id}"),
        ("POST", "/games"),
        ("GET", "/games"),
        ("GET", "/games/{game_id}"),
        ("PATCH", "/games/{game_id}"),
        ("DELETE", "/games/{game_id}"),
        ("POST", "/bookings"),
        ("GET", "/bookings"),
        ("GET", "/bookings/{booking_id}"),
        ("PATCH", "/bookings/{booking_id}"),
        ("POST", "/game-participants"),
        ("GET", "/game-participants"),
        ("GET", "/game-participants/{participant_id}"),
        ("PATCH", "/game-participants/{participant_id}"),
        ("POST", "/waitlist-entries"),
        ("GET", "/waitlist-entries"),
        ("GET", "/waitlist-entries/{waitlist_entry_id}"),
        ("PATCH", "/waitlist-entries/{waitlist_entry_id}"),
        ("POST", "/payments"),
        ("GET", "/payments"),
        ("GET", "/payments/{payment_id}"),
        ("PATCH", "/payments/{payment_id}"),
        ("POST", "/refunds"),
        ("GET", "/refunds"),
        ("GET", "/refunds/{refund_id}"),
        ("PATCH", "/refunds/{refund_id}"),
        ("POST", "/host-deposits"),
        ("GET", "/host-deposits"),
        ("GET", "/host-deposits/{host_deposit_id}"),
        ("PATCH", "/host-deposits/{host_deposit_id}"),
        ("POST", "/game-chats"),
        ("GET", "/game-chats"),
        ("GET", "/game-chats/{game_chat_id}"),
        ("PATCH", "/game-chats/{game_chat_id}"),
        ("POST", "/chat-messages"),
        ("GET", "/chat-messages"),
        ("GET", "/chat-messages/{chat_message_id}"),
        ("PATCH", "/chat-messages/{chat_message_id}"),
        ("POST", "/notifications"),
        ("GET", "/notifications"),
        ("GET", "/notifications/{notification_id}"),
        ("PATCH", "/notifications/{notification_id}"),
        ("POST", "/game-status-history"),
        ("GET", "/game-status-history"),
        ("GET", "/game-status-history/{history_id}"),
        ("PATCH", "/game-status-history/{history_id}"),
        ("POST", "/booking-status-history"),
        ("GET", "/booking-status-history"),
        ("GET", "/booking-status-history/{history_id}"),
        ("PATCH", "/booking-status-history/{history_id}"),
        ("POST", "/participant-status-history"),
        ("GET", "/participant-status-history"),
        ("GET", "/participant-status-history/{history_id}"),
        ("PATCH", "/participant-status-history/{history_id}"),
        ("POST", "/admin-actions"),
        ("GET", "/admin-actions"),
        ("GET", "/admin-actions/{admin_action_id}"),
        ("PATCH", "/admin-actions/{admin_action_id}"),
    }

    assert expected_routes <= registered_routes