import { getUserDisplayName } from './gameUserSelectors.js'
import { GUEST_JOIN_MESSAGE } from './gameDetailsConstants.js'
import { GAME_CHAT_MESSAGE_MAX_LENGTH } from './gameDetailsConstants.js'

export function buildGameDetailsLayoutProps({
  actions,
  activeImageIndex,
  activePlayerTab,
  chatDraft,
  chatError,
  chatMessages,
  chatSenderNames,
  closeChat,
  currentGuestCount,
  currentParticipant,
  currentUser,
  game,
  handleOpenChat,
  handleSendChatMessage,
  hasUnreadChat,
  images,
  isAddingHostGuest,
  isCancelGameModalOpen,
  isCancellingGame,
  isChatOpen,
  isHostGuestModalOpen,
  isLeaveModalOpen,
  isLeaving,
  isPlayerListOpen,
  isSendingChatMessage,
  isUpdatingGuests,
  joinNotice,
  latestChatMessage,
  navigate,
  participantSummary,
  setActiveImageIndex,
  setActivePlayerTab,
  setChatDraft,
  setIsCancelGameModalOpen,
  setIsHostGuestModalOpen,
  setIsLeaveModalOpen,
  setIsPlayerListOpen,
  shareCopied,
  viewModel,
}) {
  if (!viewModel) {
    return null
  }

  return {
    ...viewModel,
    activeImageIndex,
    activePlayerTab,
    chatDraft,
    chatError,
    chatMessageMaxLength: GAME_CHAT_MESSAGE_MAX_LENGTH,
    chatMessages,
    chatSenderNames,
    currentGuestCount,
    currentParticipant,
    currentUser,
    currentUserName: getUserDisplayName(currentUser),
    game,
    guestJoinMessage: GUEST_JOIN_MESSAGE,
    hasUnreadChat,
    images,
    isAddingHostGuest,
    isCancelGameModalOpen,
    isCancellingGame,
    isChatOpen,
    isHostGuestModalOpen,
    isLeaveModalOpen,
    isLeaving,
    isPlayerListOpen,
    isSendingChatMessage,
    isUpdatingGuests,
    joinNotice,
    latestChatMessage,
    onAddBookingGuests: actions.handleAddBookingGuests,
    onBackToGames: () => navigate('/games'),
    onCancelGame: actions.handleCancelGame,
    onChangeChatDraft: setChatDraft,
    onCloseCancelGameModal: () => setIsCancelGameModalOpen(false),
    onCloseChat: closeChat,
    onCloseHostGuestModal: () => setIsHostGuestModalOpen(false),
    onCloseLeaveModal: () => setIsLeaveModalOpen(false),
    onClosePlayerList: () => setIsPlayerListOpen(false),
    onJoin: actions.handleJoinIntent,
    onLeaveGame: actions.handleLeaveGame,
    onNextImage: actions.handleNextImage,
    onOpenCancelGameModal: () => setIsCancelGameModalOpen(true),
    onOpenChat: handleOpenChat,
    onOpenHostGuestModal: () => setIsHostGuestModalOpen(true),
    onOpenLeaveModal: () => setIsLeaveModalOpen(true),
    onOpenPlayerList: () => setIsPlayerListOpen(true),
    onPreviousImage: actions.handlePreviousImage,
    onRemoveGuests: actions.handleRemoveGuests,
    onSaveHostGuestCount: actions.handleSaveHostGuestCount,
    onSelectImage: setActiveImageIndex,
    onSelectPlayerTab: setActivePlayerTab,
    onSendChatMessage: handleSendChatMessage,
    onShare: actions.handleShareGame,
    participantSummary,
    shareCopied,
  }
}
